# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-25 22:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('isocc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ISPointCodes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ispc', models.CharField(max_length=12)),
                ('dec', models.IntegerField()),
                ('sigpoint_name', models.CharField(max_length=100)),
                ('sigpoint_operator', models.CharField(max_length=250)),
                ('sigpoint_country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='isocc.CountryIso')),
            ],
        ),
    ]
