# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 16:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ispc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ispointcodes',
            name='sigpoint_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
